// <auto-generated />
using System;
using FiscalFrontier.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FiscalFrontier.API.Migrations.AuthDb
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20241006202007_SeededUserSecurityQuestionsForSeededUsers")]
    partial class SeededUserSecurityQuestionsForSeededUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FiscalFrontier.API.Models.Domain.SecurityQuestions", b =>
                {
                    b.Property<int>("securityQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("securityQuestionId"));

                    b.Property<string>("securityQuestion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("securityQuestionId");

                    b.ToTable("SecurityQuestions");

                    b.HasData(
                        new
                        {
                            securityQuestionId = 1,
                            securityQuestion = "What was the first exam you failed?"
                        },
                        new
                        {
                            securityQuestionId = 2,
                            securityQuestion = "What was your Mother/Father's first car brand?"
                        },
                        new
                        {
                            securityQuestionId = 3,
                            securityQuestion = "What was the name of your siblings favorite stuffed animal?"
                        },
                        new
                        {
                            securityQuestionId = 4,
                            securityQuestion = "In what city was your Grandmother or Grandfather born?"
                        });
                });

            modelBuilder.Entity("FiscalFrontier.API.Models.Domain.UserSecurityQuestion", b =>
                {
                    b.Property<int>("userSecurityQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userSecurityQuestionId"));

                    b.Property<string>("answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("securityQuestionId")
                        .HasColumnType("int");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("userSecurityQuestionId");

                    b.HasIndex("securityQuestionId");

                    b.HasIndex("userId");

                    b.ToTable("UserSecurityQuestions");

                    b.HasData(
                        new
                        {
                            userSecurityQuestionId = 1,
                            answer = "Accounting 101",
                            securityQuestionId = 1,
                            userId = "dc1fa6d7-e0a9-475a-bdcb-f9ce52ea3e84"
                        },
                        new
                        {
                            userSecurityQuestionId = 2,
                            answer = "Porsche",
                            securityQuestionId = 2,
                            userId = "dc1fa6d7-e0a9-475a-bdcb-f9ce52ea3e84"
                        },
                        new
                        {
                            userSecurityQuestionId = 3,
                            answer = "Clifford the Big Red Dog",
                            securityQuestionId = 3,
                            userId = "dfc5d997-71da-4f11-8ec9-f15065a717e9"
                        },
                        new
                        {
                            userSecurityQuestionId = 4,
                            answer = "Marietta, Georgia",
                            securityQuestionId = 4,
                            userId = "dfc5d997-71da-4f11-8ec9-f15065a717e9"
                        },
                        new
                        {
                            userSecurityQuestionId = 5,
                            answer = "Nissan",
                            securityQuestionId = 1,
                            userId = "7986a011-569b-42e2-8c72-aceec91935b6"
                        },
                        new
                        {
                            userSecurityQuestionId = 6,
                            answer = "Atlanta, Georgia",
                            securityQuestionId = 4,
                            userId = "dc1fa6d7-e0a9-475a-bdcb-f9ce52ea3e84"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "18ba9546-05ff-44a7-b1e3-ba79f546f06b",
                            ConcurrencyStamp = "18ba9546-05ff-44a7-b1e3-ba79f546f06b",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "ee8190d1-63cd-4c9c-bea4-2d4252de752b",
                            ConcurrencyStamp = "ee8190d1-63cd-4c9c-bea4-2d4252de752b",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = "8d6430ec-2c87-4ca9-bc3a-b5025a41d8c9",
                            ConcurrencyStamp = "8d6430ec-2c87-4ca9-bc3a-b5025a41d8c9",
                            Name = "Accountant",
                            NormalizedName = "ACCOUNTANT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "dc1fa6d7-e0a9-475a-bdcb-f9ce52ea3e84",
                            RoleId = "18ba9546-05ff-44a7-b1e3-ba79f546f06b"
                        },
                        new
                        {
                            UserId = "dc1fa6d7-e0a9-475a-bdcb-f9ce52ea3e84",
                            RoleId = "ee8190d1-63cd-4c9c-bea4-2d4252de752b"
                        },
                        new
                        {
                            UserId = "dc1fa6d7-e0a9-475a-bdcb-f9ce52ea3e84",
                            RoleId = "8d6430ec-2c87-4ca9-bc3a-b5025a41d8c9"
                        },
                        new
                        {
                            UserId = "dfc5d997-71da-4f11-8ec9-f15065a717e9",
                            RoleId = "ee8190d1-63cd-4c9c-bea4-2d4252de752b"
                        },
                        new
                        {
                            UserId = "dfc5d997-71da-4f11-8ec9-f15065a717e9",
                            RoleId = "8d6430ec-2c87-4ca9-bc3a-b5025a41d8c9"
                        },
                        new
                        {
                            UserId = "7986a011-569b-42e2-8c72-aceec91935b6",
                            RoleId = "ee8190d1-63cd-4c9c-bea4-2d4252de752b"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FiscalFrontier.API.Models.Domain.User", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("passwordExpirationDate")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("User");

                    b.HasData(
                        new
                        {
                            Id = "dc1fa6d7-e0a9-475a-bdcb-f9ce52ea3e84",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "075576b4-41a2-4b04-8912-09f4410fd0ae",
                            Email = "adminAccount@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMINACCOUNT@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEQtpXvPdmfUDSR1x3UViM91GhSWoyEVx1nDiuH6YvnU7TwJLcpG0M+aNc3YJpckAA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8df4cea3-6691-4623-9bb4-8a6b2e0a487f",
                            TwoFactorEnabled = false,
                            UserName = "AAccount0924",
                            address = "1100 South Marietta Pkwy SE, Marietta, GA 30060",
                            createdDate = new DateTime(2024, 10, 6, 20, 20, 7, 509, DateTimeKind.Utc).AddTicks(1788),
                            dateOfBirth = new DateTime(2003, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            firstName = "Admin",
                            isActive = true,
                            lastName = "SAccount",
                            passwordExpirationDate = new DateTime(2025, 1, 6, 20, 20, 7, 509, DateTimeKind.Utc).AddTicks(1792)
                        },
                        new
                        {
                            Id = "dfc5d997-71da-4f11-8ec9-f15065a717e9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8fa70163-b1d9-4018-bf3e-1020d645f764",
                            Email = "managerAccount@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MANAGERACCOUNT@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGi9qzGH0Zq7n3EVWUFoBeLlJfzJkd0Q4RlNICzkg/8M8cUVo1xIAWlAyDISQFZIAw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "726424bf-4044-4fce-8883-3b28e9a6fc39",
                            TwoFactorEnabled = false,
                            UserName = "MAccount0924",
                            address = "1100 South Marietta Pkwy SE, Marietta, GA 30060",
                            createdDate = new DateTime(2024, 10, 6, 20, 20, 7, 509, DateTimeKind.Utc).AddTicks(1807),
                            dateOfBirth = new DateTime(2003, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            firstName = "Manager",
                            isActive = true,
                            lastName = "Account",
                            passwordExpirationDate = new DateTime(2025, 1, 6, 20, 20, 7, 509, DateTimeKind.Utc).AddTicks(1807)
                        },
                        new
                        {
                            Id = "7986a011-569b-42e2-8c72-aceec91935b6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "388df760-d93f-42b9-a820-f6903172798e",
                            Email = "accountantAccount@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ACCOUNTANTACCOUNT@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHnv4i/xUHpcsdjoOfzxLqgBKy1hpCBiB8uUyH9WvQRtjnXCp8PiYtCgGCApC3Ndbg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b69bd6f7-eef7-4bbf-b2cc-e920ec012bed",
                            TwoFactorEnabled = false,
                            UserName = "AAccount0824",
                            address = "1100 South Marietta Pkwy SE, Marietta, GA 30060",
                            createdDate = new DateTime(2024, 10, 6, 20, 20, 7, 509, DateTimeKind.Utc).AddTicks(1812),
                            dateOfBirth = new DateTime(2003, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            firstName = "Accountant",
                            isActive = true,
                            lastName = "Account",
                            passwordExpirationDate = new DateTime(2025, 1, 6, 20, 20, 7, 509, DateTimeKind.Utc).AddTicks(1813)
                        });
                });

            modelBuilder.Entity("FiscalFrontier.API.Models.Domain.UserSecurityQuestion", b =>
                {
                    b.HasOne("FiscalFrontier.API.Models.Domain.SecurityQuestions", "securityQuestion")
                        .WithMany()
                        .HasForeignKey("securityQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FiscalFrontier.API.Models.Domain.User", "user")
                        .WithMany("securityQuestions")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("securityQuestion");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FiscalFrontier.API.Models.Domain.User", b =>
                {
                    b.Navigation("securityQuestions");
                });
#pragma warning restore 612, 618
        }
    }
}
